# Basic
title: Guihong WAN
subtitle: Dream Big Work Hard Repeat
description: Welcome to my website
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: ghwan
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Data Analysis/Machine learning
url: "https://guihongwan.github.io"

# Comment
comment:
    duoshuo: guihongwan 

# Social
social:
    # weibo: 
    github: guihongwan
    # twitter: 
    mail: guihong.wan@utdallas.edu

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-84134159-3   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Main

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About me, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


